tools: Drop Python 2.7 support
Rename `_stop` to `_stop_event` because `_stop` is now an internal
attribute in `Threading.thread` and leads to the error:
TypeError: 'Event' object is not callable