tools: Update weather_station.py to Python 3.5
Update to Python 3.5 and fix errors:
- C0411: standard import "import X" comes before "import serial"
- Fix version of graphitesend to 0.3.4, as newer ones fail with
  "AttributeError: 'module' object has no attribute 'init'"
  (https://github.com/daniellawrence/graphitesend/issues/59)